### PR TITLE
fix OverflowException

### PR DESCRIPTION
**Pull request by 297498075**
VLB{EQ8J0~H(1{N6JO(5OQO
1CMD{Z8G5A XU6AZ@}BJB7N

This is what I appeared during testing.

### CODE REVIEW

**Comment by miroslavpejic85** [comment]
Hello @297498075, 
Hello, thank you, just a question what is the diff between:           
```
 byte * pScan0 = (byte *) Scan0.ToInt64 ();
```
and
```
byte * pScan0 = (byte *) Convert.ToInt64 (Scan0.ToString ());
```
After this fix, are you sure you have not broken anything else?
Thanks so much.

**Comment by 297498075** [comment]
Both are OK at run time, but not at debug time
G5TW68UGW)BSWI1U(9(U$12
P_XP6W@ FKQSL)_$J36F$PQ

Of course, this may be due to my IDE's question, I chose a way to display it correctly when debugging

**Comment by 297498075** [comment]
I looked at the decompiled code, and the conversion here seems redundant

**Comment by miroslavpejic85** [comment]
Try also this:

```csharp
byte* pScan0;
if (IntPtr.Size == 8)
{
    // 64 bit process
    pScan0 = (byte*)Scan0.ToInt64();
}
else
{
    // 32 bit process
    pScan0 = (byte*)Scan0.ToInt32();
}

if (!outStream.CanWrite)
{
    throw new Exception("Must have access to Write in the Stream");
}
```

**Comment by 297498075** [comment]
Oh,this is certainly more rigorous.
But please see my usage.I think this is more simple.
Can you tell me more about the conversion and the non-conversion?
``` C#
byte* pScan0 = (byte*)Scan0;
```

**Comment by miroslavpejic85** [comment]
Hey @297498075, I'm back
So you confirm to me this final solution?
```bash
byte* pScan0 = (byte*)Scan0;
```
Thanks for the time you took on this fix ;)

**Comment by 297498075** [comment]
yes,it work

**Pull request merged**
