### PR TITLE
Ported project to .NET 8

### PR DESCRIPTION
**Pull request by KieranDevvs**
This PR is the start of my plans to make this cross platform. I'm going to start refactoring a lot of the code so that its possible to plug in a more UI providers (other than WinForms). It should also neaten up the code base a fair amount.

- Removed dependency on `Newtonsoft.Json` by moving to `System.Text.Json`
- Refactored stun server `IO` calls to be `async`

### CODE REVIEW

**Comment by webRTCv1** [comment]
Hey @KieranDevvs!

Thank you so much for this PR!

I've created a new branch (`develop`) for your work. I will review and test your changes with .NET 8, and continue merging them into this branch.

When I have more time, I'll set up a Windows OS to test your updates. In the meantime, have you already tested and compiled your changes on Windows?

Thanks again for your contributions!

**Comment by miroslavpejic85** [comment]
Hey @KieranDevvs!

Thank you so much for this PR!

I've created a new branch (`develop`) for your work. I will review and test your changes with .NET 8, and continue merging them into this branch.

When I have more time, I'll set up a Windows OS to test your updates. In the meantime, have you already tested and compiled your changes on Windows?

Thanks again for your contributions!

**Comment by KieranDevvs** [comment]
> Hey @KieranDevvs!
> 
> Thank you so much for this PR!
> 
> I've created a new branch (`develop`) for your work. I will review and test your changes with .NET 8, and continue merging them into this branch.
> 
> When I have more time, I'll set up a Windows OS to test your updates. In the meantime, have you already tested and compiled your changes on Windows?
> 
> Thanks again for your contributions!

I've compiled and tested it as much as I can with one machine, but as you can imagine, its quite tricky to control the desktop from the same machine.
image

**Comment by miroslavpejic85** [comment]
> I've compiled and tested it as much as I can with one machine, but as you can imagine, its quite tricky to control the desktop from the same machine. 

Yeah, I understand how challenging that can be! :)

> Merging it to a development branch is fine. Ill try and separate the pull requests out as much as I can to make it easier to review.

That sounds great. I'll go ahead and merge your changes into the development branch. Thanks for your efforts in separating the pull requests to facilitate the review process. Your time and hard work are much appreciated!

**Pull request merged**
